/* **********************************************************************************************
*  Macro SCSASCode: Modified from Credit Risk Scorecards: Development and 
*	Implementation using SAS. It writes the scorecard generated by the scorecard dataset 
*    to an output file FileName generating CSV format readable by MS Excel. 
*  If The option IntOpt=1 then we convert the points to integer values
  otherwise they are left as numbers
* **********************************************************************************************/
%macro SCCSVcode(scdn,BasePoints, BaseOdds, PDO,FileName, IntOpt);
	/* direct the output to the filename */
	proc sort data=&scdn;
		by model_item bin;
	run;

	data _null_;
		set &scdn nobs=nx;
		by model_item bin;
		file "&pout.&filename..csv";
		length cond $300.;

		if _N_ =1 then do;
			put 'Automatically Generated Scorecard , , , , , ';
			put 'Scorecard Scale, , , , ';
			put "Odds, 1, to,  &BaseOdds ,  at , &BasePoints , Points,  PDO,  &PDO, , , ,  ";
		end; 

		%if &IntOpt=1 %then xPoints=int(Points);
		%else xPoints=Points; ;

		if upcase(model_item)="INTERCEPT"  then do;
			put ' ,,,,,, Points ';
			put ' ,,,,,, =======';
			put "Base Points, ,,,,," xPoints;
		end;
		else do;
			if first.model_item then do;
				put ori_var ", , , ,";
				put '--------------, , , ,';
			end;

			/* The rule */
			if  not missing(border) then  do;/* continuous */
				if last.model_item then cond=',,,,> ,'||border;
				else cond=',,,,<=,'||border ;
			end; 
			else if not missing(ori_val) then/* cluster nominal */			
				cond = ',,, in ('|| compbl(ori_val) || "),,"; 
			else /* nominal numeric */
				cond=' ,, ,'|| compress(bin)|| ",,"; 

			put "      " cond ", " xPoints;
		 end;
	run;
%mend;

