/* **********************************************************************************************
*  Macro SCSASCode: Modified from Credit Risk Scorecards: Development and 
*	Implementation using SAS. It writes the scorecard generated by the scorecard dataset 
*    to an output file FileName generating SQL SELECT statement. 
*  If The option IntOpt=1 then we convert the points to integer values
  otherwise they are left as numbers
* **********************************************************************************************/
%macro SCSQLCode(scdn,BasePoints, BaseOdds, PDO,FileName, IntOpt);
	/* direct the output to the filename */
	proc sort data=&scdn;
		by model_item bin;
	run;

	data _null_;
		set &scdn nobs=nx;
		by model_item bin;
		file "&pout.&filename..sql";
		length cond $300.;

		if _N_ =1 then do;
			put '/***** Automatically Generated Scorecard Code*****/';
			put;
			put '/* Scorecard Scale : ';
			put "/*   Odds of [ 1 : &BaseOdds ] at  [ &BasePoints ] Points with PDO of [ 20 ] */ ";
			put '/*********************************************/';
			put;
			put '/****  Modify this code at the end to by adding the name of the  */';
			put '/****  the new score variable and the table name where these fields */';
			put '/****  would reside at time of deployment */';
			put;
			put 'SELECT (';
		end; 

		/* print the dataset RulesDS */
		%if &IntOpt=1 %then xPoints=int(Points);
		%else xPoints=Points; ;

		if upcase(model_item)="INTERCEPT" then do;
			put '/***************Base Points********************/';
			put "   "  xPoints ;
		end;
		else do;
			if first.model_item then do;
				put "/***********  Variable : " ori_var "    *************/";
				put '+ (CASE ';
	      	end;

			/* The rule */
			if not missing(border) then  do;/* continuous */
				if last.model_item then cond='   else ('||xPoints||')';
				else cond='   WHEN '||compress(ori_var)||' <= ('||compress(border) || ') THEN ('||xPoints||')';  
			end; 
			else if not missing(ori_val) then do;/* cluster nominal */
				if last.model_item then cond = '   ELSE ('||xPoints||')' ; 
				else cond = '   WHEN '||compress(ori_var)|| ' in (' || compbl(ori_val) ||') THEN ('||xPoints||')' ; 
			end;
			else do;/* nominal numeric */
				if last.model_item then cond='   ELSE (' ||xPoints||')'; 
				else cond='   WHEN ' ||compress(ori_var)|| '==' || compress(bin)|| 'THEN ('||xPoints||')'; 
			end;
			put "      " cond;

			if last.model_item then put '  END)';
		end;

		if _N_=Nx then do;
			put '  )';
			put ' AS MyScore'; 
			put ' FROM  MyTable;';  
			put;
			put '/* Modify the variable name and the table to match the data schema */';
			put;
		end;
	run;
%mend;

